[symlinks]
# Format:
# 'source' = 'destination'
"npmrc" = "~/.npmrc"
'vimrc' = '~/.vimrc'
'inputrc' = '~/.inputrc'
'alacritty.yml' = '~/.config/alacritty/alacritty.yml'
'init.vim' = '~/.config/nvim/init.vim'
'bashrc' = '~/.bashrc'
'bash_files' = '~/.bash_files'
'bash_profile' = '~/.bash_profile'
'gitconfig' = '~/.gitconfig'
'tmux.conf' = '~/.tmux.conf'
'scripts/tmux-vim-select-pane' = "~/.local/bin/tmux-vim-select-pane"

[optional]
source_prefix = "~/code/dotfiles"
git_remote = 'https://github.com/samdixon/dotfiles'
