[symlinks]
# Format:
# 'source' = 'destination'
"npmrc" = "~/.npmrc"
'vimrc' = '~/.vimrc'
'inputrc' = '~/.inputrc'
'bashrc' = '~/.bashrc'
'bash_files' = '~/.bash_files'
'bash_profile' = '~/.bash_profile'
'gitconfig' = '~/.gitconfig'
'tmux.conf' = '~/.tmux.conf'
'bin/tmux-vim-select-pane' = "~/.local/bin/tmux-vim-select-pane"
'bin' = "~/bin"
'!~/Dropbox/sjd' = '~/sjd'

[optional]
source_prefix = "~/sjd/code/dotfiles"
git_remote = 'https://github.com/samdixon/dotfiles'
